apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-image-updater
  namespace: argocd
  annotations:
    # IRSA role that grants ECR read access.
    # Set this to the Terraform output `argocd_image_updater_role_arn`.
    eks.amazonaws.com/role-arn: REPLACE_ME_ARGOCD_IMAGE_UPDATER_ROLE_ARN

