apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/mmg-global/ironforge.git
    targetRevision: main
    path: src/platform/deploy/kustomize/cluster-autoscaler/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

